global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8090"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8096"]

  - job_name: movie-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["movie-service:8091"]

  - job_name: theater-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["theater-service:8092"]

  - job_name: showtime-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["showtime-service:8093"]

  - job_name: booking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["booking-service:8094"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8095"]
